---
title: "Analysis of JAR Size in Original and Specialized Dependencies"
author: César Soto Valero
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    df_print: paged
    css: css/main.css
    number_sections: true
    toc: true
    toc_depth: 3
    toc_float: 
      collapsed: false
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Import the header 
source("0_header.R")
# Clear the R environment
rm(list=ls())
```

# Dataset

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Read the data
original_deps <- read.delim("../../pipeline/csv/original-deps.csv", sep = ",", header = T, stringsAsFactors = TRUE)
specialized_deps <- read.delim("../../pipeline/csv/specialized-deps.csv", sep = ",", header = T, stringsAsFactors = TRUE)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
data <- inner_join(original_deps,specialized_deps, by=c("Project","Dependency")) %>% 
  rename("SizeOriginal" = "Size.x", "SizeSpecialized" = "Size.y") %>% 
  select("Project", "Dependency","SizeOriginal","SizeSpecialized")

```


```{r echo=FALSE, message=FALSE, warning=FALSE}
data %>% 
  arrange(desc(SizeOriginal)) %>% 
  mutate(SizeOriginal = SizeOriginal/1000, SizeSpecialized = SizeSpecialized/1000)

```

# Number of specialized dependencies in projects

```{r echo=FALSE, message=FALSE, warning=FALSE}
data %>% 
  count(Project) %>%
  ggplot(aes(x = reorder(Project, n), y = n)) +
  geom_bar(stat = 'identity', fill = "#009ade") +
  xlab("Project") +
  ylab("#Specialized dependencies") +
  coord_flip()
```

# Size of JARs in specialized versions

```{r echo=FALSE, message=FALSE, warning=FALSE}
data %>% 
  group_by(Project) %>% 
  summarise(Original = sum(SizeOriginal), Specialized = sum(SizeSpecialized)) %>% 
  gather(key = "Type", value = "Size", 2:3) %>% 
  mutate(Size = Size/1000) %>% 
  ggplot(aes(x = reorder(Project, Size), y = Size, fill = Type)) +
    geom_bar(stat = 'identity', position = position_dodge()) +
    scale_y_continuous(labels = label_comma()) +
    scale_fill_manual(values=c( "#ff1f5d", "#00cd6c", "#009ade")) +
    xlab("Project") +
    ylab("Total size (KiB)") +
    coord_flip()
```

# Percentage of size reduction in specialized versions

```{r echo=FALSE, message=FALSE, warning=FALSE}
data %>% 
  group_by(Project) %>% 
  summarise(Original = sum(SizeOriginal), Specialized = sum(SizeSpecialized)) %>% 
  mutate(Reduction = (((Original-Specialized)*100)/Original)/100) %>% 
  ggplot(aes(x = reorder(Project, Reduction), y = Reduction)) +
  geom_bar(stat = 'identity', fill = "#f28522") +
  xlab("Project") +
  scale_y_continuous(labels = scales::percent) +
  ylab("Size reduction") +
  coord_flip()
```
