---
title: "Analysis of Classes in Original and Specialized Dependencies"
author: César Soto Valero
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    df_print: paged
    css: css/main.css
    number_sections: true
    toc: true
    toc_depth: 3
    toc_float: 
      collapsed: false
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Import the header 
source("0_header.R")
# Clear the R environment
rm(list=ls())
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
# Read the data
deptrim_logs <- read.delim("../../pipeline/csv/deptrim-logs.csv", sep = ",", header = T, stringsAsFactors = TRUE)
```

```{r echo=FALSE, warning=FALSE}
data <- deptrim_logs %>% 
  select("Project", "Dependency","RemovedTypes","TotalTypes") %>% 
  rename("OriginalTypes" = "TotalTypes")
```

# Number of classes in specialized versions

```{r echo=FALSE, message=FALSE, warning=FALSE}
data %>% 
  group_by(Project) %>% 
  summarise(Original = sum(OriginalTypes), Specialized = sum(RemovedTypes)) %>% 
  gather(key = "Type", value = "Types", 2:3) %>% 
  mutate(Types = Types) %>% 
  ggplot(aes(x = reorder(Project, Types), y = Types, fill = Type)) +
    geom_bar(stat = 'identity', position = position_dodge()) +
    scale_y_continuous(labels = label_comma()) +
    scale_fill_manual(values=c( "#ff1f5d", "#00cd6c", "#009ade")) +
    xlab("Project") +
    ylab("Total classes") +
    coord_flip()
```

# Percentage of classes reduction in specialized versions

```{r echo=FALSE, message=FALSE, warning=FALSE}
data %>% 
  group_by(Project) %>% 
  summarise(Original = sum(OriginalTypes), Specialized = sum(RemovedTypes)) %>% 
  mutate(Reduction = (((Original-Specialized)*100)/Original)/100) %>% 
  ggplot(aes(x = reorder(Project, Reduction), y = Reduction)) +
  geom_bar(stat = 'identity', fill = "#f28522") +
  xlab("Project") +
  scale_y_continuous(labels = scales::percent) +
  ylab("#Classes reduction") +
  coord_flip()
```
